### PR TITLE
Make maxmerge and minface world variables

### PR DESCRIPTION
**Pull request by acerspyro**
See https://github.com/red-eclipse/base/issues/715
Also my text editor seems to have removed a bunch of trailing spaces automatically, I hope this won't cause any problems.

### CODE REVIEW

**Comment by qreeves** [comment]
@lsalzman can you please confirm if this is OK to do, or if there are any caveats that make this not a good idea to implement?

**Comment by lsalzman** [comment]
I guess the original intent was that this should be set in map cfgs explicitly. But technically it will still work as a world variable.

**Comment by acerspyro** [comment]
Are there any other variables that can be set as a world variable?

**Comment by TheAssassin** [comment]
Is that just me, or does @lsalzman's comment read like we shouldn't have merged it because the change doesn't provide what was expected?

**Pull request merged**
