### PR TITLE
Let mouse leave game's window. Close #701.

### LINKED ISSUE #701: Missing button to release the mouse
Older versions of the game used to feature a mouse release button on the F9 (?) key.

The fact that this key is now missing is extremely irritating in conjunction with the fact that the game automatically minimizes itself upon alt-tab. This prevents me from right-clicking its titlebar to change the window to Fullscreen in KDE. Even if I can get the menu to open via Alt + F3, it cannot be controlled, as the game also captures the keyboard.

The best fix would be to let the mouse leave the window if it goes beyond the edge of the window.

### PR DESCRIPTION
**Pull request by zaquest**
This works by not grabbing mouse for anything but camera control and syncronizing system's and game's cursors when necessary.

### CODE REVIEW

**Comment by acerspyro** [comment]
Could you make the in-game cursor disappear when the mouse leaves the window?

**Comment by lsalzman** [comment]
This looks like it will break grabbing and also not properly interact with alt-tabbing and such on all operating systems. Not a fan of this.

**Comment by qreeves** [comment]
Yeah, we need to be really careful with the input stuff due to individual operating system quirks. It is on my list of things to look at though.

**Comment by Calinou** [comment]
Also, make sure it still works with multi-monitor setups.

**Pull request closed without merging**
