### PR TITLE
OpenBSD/rm command line does not support verbose flag

### PR DESCRIPTION
**Pull request by devnexen**
... as the port uses the old Makefile way, it is useful :-)

### CODE REVIEW

**Comment by acz13** [comment]
Is this only OpenBSD?

**Comment by devnexen** [comment]
FreeBSD supports it

**Comment by TheAssassin** [comment]
I checked with the man entries and yeah, OpenBSD's `rm` does not support `-v`. I didn't check for other BSD flavors, as this PR is explicitly fixing the issue for OpenBSD.
We can always add other BSDs or Linux distros later.

**Comment by qreeves** [comment]
Thanks for implementing this in a portable way!

**Pull request merged**
