### PR TITLE
Bomber-ball poll results implementation. Close #569.

### LINKED ISSUE #569: Change bomber-ball behaviour based on poll results
From: http://redeclipse.net/forum/viewtopic.php?f=4&t=956

> Currently in basket bomberball, you have to throw the ball into the goal to score a point.
> 
> I'm suggesting this should be opened up to how it was in 1.4, throw in or run in. It's far too easy in basket bomberball to just stand on your goal, acting as a 100% efficient goalie and your extra hard to kill due to flag buff, with a bit of running around it's pretty damn hard. True, you could displace players with flamer2 or plasma2, but that becomes infeasible with higher numbers of players (where this becomes a harder and harder problem) and overall its kind of an uncool game mechanic.

There is also the idea of giving 1 point for "touchdowns" and 3 points for "throw-ins" from a distance.

### PR DESCRIPTION
**Pull request by zaquest**
Changes defaults for `bomberbasketonly` and `bomberbasketmindist` to match poll results. Adds two variables `bomberthrowinpoints` and `bombertouchdownpoints` which are respectively a number of points team gets for throw-in and for touchdown.

### CODE REVIEW

**Comment by qreeves** [comment]
I can't seem to find the forum topic, can you provide a link?

**Comment by zaquest** [comment]
Issue #569. Forum topic http://redeclipse.net/forum/viewtopic.php?f=4&t=956

**Comment by qreeves** [comment]
Ah yes, thanks 😄

**Comment by JeffBobbo** [comment]
16m distance might be a but big for smaller maps or maps with enclosed bases (e.g., erosion, bath and keystone2k).

Other than that, yay!

**Pull request merged**
