### PR TITLE
enable commands and aliases in the vars menu

### PR DESCRIPTION
**Pull request by bonifarz**
Use the vars menu to find commands and aliases, too.
For details, see the commit notes.

### CODE REVIEW

**Comment by bonifarz** [comment]
I just realized that getvarinfo used for the vars menu can be applied to commands and aliases - that's cool! Usually if someone wants to search variables for a certain topic or keyword, aliases and commands are interesting to look up, too. With a few fixes to the menu, this seems to work pretty well. It does not make sense to "edit" aliases or commands in this menu, but hey, we can pass the search reult to the console :smiley: 
What do you think?

**Comment by qreeves** [comment]
You should probably use `guibitfield` for the bitwise operators like `$varnotypes`, etc.

**Comment by bonifarz** [comment]
Did so for testing, and left that as a comment, https://github.com/bonifarz/base/blob/patch-5/config/menus/vars.cfg#L11-36
So, the point is that two guibitfields (for varnotypes of commands and aliases) are better than one checkbox? Or should we add more options. Not sure how much space should be used for this.

**Comment by qreeves** [comment]
If you're modifying a bitwise variable then you should always use the bit operators. This way the user can modify the value manually without losing their setting when pressing these buttons.

**Comment by bonifarz** [comment]
Good point. And I guess it does not hurt to have checkboxes to narrow down the variable types. There seems to be enough room for that anyway.

**Pull request merged**
