### PR TITLE
A hidden variable for servers.

### PR DESCRIPTION
**Pull request by shacknetisp**
The variable is transmitted via `addserver`.
Clients will only see servers with 'hidden=1' if they enable `listhidden`.
The purpose of this is to allow servers to be modified heavily and still be listed on the master server, while giving new players the best experience.

Idea from http://forum.freegamedev.net/viewtopic.php?f=53&t=2998

### CODE REVIEW

**Comment by Calinou** [comment]
:+1:

**Comment by nyuszika7h** [comment]
Sounds good.

**Comment by shirepirate** [comment]
as i see it, the guidelines for connecting to the master server are the guidelines for connecting to the master server. they wouldn't change with this implemented, so what would be the point? wouldn't it be better for servers to be more visible?

**Comment by shacknetisp** [comment]
It would give servers with unauthorized modifications, (such as the one mentioned [here](http://redeclipse.net/forum/viewtopic.php?f=4&t=324)) the ability to be listed. This would, however, require an amendment to the guidelines to allow for hidden servers to use unauthorized modifications.

From the [Old Trac Open Issues](http://redeclipse.net/forum/viewtopic.php?f=9&t=8) topic:

>**Master Server Policy Follow-ups**
 >*The problem*:
 >http://forum.freegamedev.net/viewtopic.php?f=53&t=2995
 >A vocal minority has problems with the level of moderation done by those with auth keys, some also  disagree with the guidelines set out by the project regarding the expectations of those using the master server.
 >*The suggested solutions*:
 >http://forum.freegamedev.net/viewtopic.php?f=53&t=2998
 >Allow server owners to apply certain flags to their configuration, defining them as "unmoderated"/"modified"/etc and restricting their view-ability on the master server list.

**Comment by shirepirate** [comment]
i'm not voting for easier viewability of servers with terrible variables like that one. but aside from that, hidden or not, they would still be listed and "unauthorized modifications" is far too vague for that to slide. the vast majority of unauthorized modifications would be those that couldn't be allowed in any case regardless, not simply stupid weapon variables like the example.

it's easy enough to set up a private server in any way you want and share it with friends / publish it on a website. and if you want it publicly listed start your own master server. a modification of the server menu to make it easier to enter in custom master servers and switch between them sounds entirely acceptable, this would require considerable effort by someone who would wish to play on such servers as opposed to a variable which one could accidentally stumble across.

**Comment by qreeves** [comment]
Yeah, it was never my intention to just let all crazy modifications on the master server. I've never made any progress on this issue because I don't feel it to be a high priority (for the project). We're focused on making *this* game, not helping others write their own and possibly giving users a bad impression of the game. This is why we defend the master server so rigorously with set guidelines; *quality assurance*.

In my opinion, any modifications that would need special permission to be on the master server would be better off as a content proposal for the game itself. I'd rather advocate open source than have to deal with each and every modified server with unshared source code.

**Comment by shacknetisp** [comment]
I probably should have made this a poll on the forum first, I see why it is not wanted.

**Pull request closed without merging**
