### PR TITLE
update usage.cfg

### PR DESCRIPTION
**Pull request by IceflowRE**
Add
- sorts: material, clients, editing, gui, lists
- getclientnum
- getclientcolour
- getclienthandle
- getclientip
- getclienthost
- getclientversion
- getclientvanity
- getclientweapselect
- getclientloadweap
- getclientteam
- listclients
- listaverage
- listaveragef
- isonline
- gamemode

Update
- guislice
- kick, allow, ban, mute, limit
- guitext
- guibutton
- case, casef, cases, cond

Sort
- edit
- setpersist
- local
- inputcommand
- max, maxf, min, minf
- *, *f, +, +f, -, -f

Please take a look at the added descriptons due to english grammar, ...

### CODE REVIEW

**Comment by IceflowRE** [comment]
Forgot

Update
- guitext
- guibutton
- case, casef, cases, cond

**Comment by bonifarz** [comment]
Why did you replace all < clientnum >  with < cn > ? I don't think that helps to understand the instructions.

**Comment by IceflowRE** [comment]
clientnum and cn is equal (ingame it shows ever clientnum)

**Comment by shirepirate** [comment]
This PR contains some improper grammar, spelling errors and poor wording. I will merge it and try to proofread it afterward, however.

**Pull request merged**
