### PR TITLE
Add getclient{points,frags,deaths,cptime} ICOMMANDs

### LINKED ISSUE #467: ability to get player deaths/kills amount by cubescript
I know its not that hard for devs to make this possible. For example I want to create a simple script for some kids (like my nephew) to auto-bot-hardness level based on these variables, but with more capabilities like:
  -bot abilities
  -bot spawn weapon
  -bot speed

I just need to get by cubescript a player deaths/kills amount.
It would be ideal to get more info - like how many times a bots killed a player and vice versa, but its not necessary :)  thanks in advance for making my request possible ;p

### PR DESCRIPTION
**Pull request by shacknetisp**
Some simple functions for accessing information about scores.
This closes #467

### CODE REVIEW

**Comment by Dziq84** [comment]
why this still is not merged ? something wrong with that ? just curious. .

**Comment by qreeves** [comment]
Code changes have to be reviewed and tested by me before being merged, I've been busy lately with my kids, Horizon, and stuff.

**Comment by graphitemaster** [comment]
It's 4 lines of code, it doesn't take an afternoon to review dude

**Comment by qreeves** [comment]
Is there some sort of employment contract I'm not aware of? I thought this was voluntary; are you going to pay me to merge pull requests now? I'll do it when I'm fucking ready, preferably when there's a few things to do at once to save diverting my focus for every damn little thing.

**Pull request closed without merging**
