### PR TITLE
Break spawn protection on cooking and affinity taking actions.

### PR DESCRIPTION
**Pull request by shacknetisp**
Players under spawn protection can gain an advantage immediately after spawning by cooking weapons or taking an affinity while still invincible, but neither of these actions break their protection.
This pull request adds two on-by-default variables (`protectbreakcook`, `protectbreakaffinity`) that cause these actions to break protection, keeping spawn protection only as a method to assess the situation and reorient rather than affect the state of the match.

The old `protectbreak` variable is moved to `protectbreakshoot` for uniformity.

Requested by @JeffBobbo

### CODE REVIEW

**Comment by TheAssassin** [comment]
I'm not so fond of switching this on by default. I don't think cooking a grenade should break the spawn protection, as this protects from spawn camping. If it broke spawn protection, one could just stand next to the spawn points, and wait for players to spawn and pick up a grenade. They can't effectively use it, as either way (cooking or throwing away) will break their protection.
I wouldn't switch that on by default, at least until the next release is published, similarly to the flag toss fix.

**Comment by acerspyro** [comment]
See #722 
Implementing a Quake 3-like method of spawning would avoid most of these spawn killing issues anyway.

**Comment by shacknetisp** [comment]
Players have three seconds after spawning to reposition themselves, they can grab explosives during this time without leaving their invincibility. Furthermore, if a player has recently died, they should not have an advantage over the attackers simply because they died.
I don't believe spawn camping is helped or hindered by this, the camper already has access to any nearby explosives, and the spawning player has those seconds of invincibility rendering any immediate attack useless. Players should not be using their spawn protection for offensive actions.

**Comment by qreeves** [comment]
Please resync so I can merge.

**Pull request merged**
