### PR TITLE
improve vars menu: Flag filters & hex values

### PR DESCRIPTION
**Pull request by bonifarz**
add proper bitfields for filtering or excluding variable flags
per default, only show the bitfield for including commands
all other bitfields go in an advanced filter panel, enabled via a checkbox
check hex colours via their flag, show the default and value as such
nicer colour preview, also for default colours

### CODE REVIEW

**Comment by bonifarz** [comment]
vars-preview

**Comment by swooboo** [comment]
Pulled it. The default is a nice addition. But I have an issue with the **flags / exclude** column,
because it is not easily understood what the first column of checkboxes does vs the second.
This is definitely a step in the right direction though. I wish it looked more like the old vars
editor...

**Comment by bonifarz** [comment]
Right, we need a better explanation, maybe with a tooltip. Suggestions are welcome.

Flags checked in the first column must be present for a var to show up in the list (i.e. like a filter, right?). Per default, this is the auto-complete flag, so user defined or temporary aliases are ignored.

The second bitfield (checkbox) includes a variable if it has the given flag. Per default, those are server vars sv_*.

Actually, the same pair of filters is available for variables types, too (vartypes/varnotypes).
I thought excluding types is not useful, but maybe the layout looks nicer with two bitfields per line.

Old vars editor: You refer to RE 1.4?

**Comment by swooboo** [comment]
Yes, I am referring to the 1.4 vars editor. Also, from your explanation I still can't get
the meaning of the checkboxes, but maybe it's just me, or maybe I just didn't explain
myself. I get what the filter is for, that's self-explanatory. What I am confused about,
is the double column of checkboxes under  **flags / exclude** - maybe I'm not used
to editing vars a lot, so I just don't know what this is. As for tooltips - that'd be nice.
I actually think every thing that can be accessed with a keyboard key should have
the key in the tooltip. (Sorry for offtopic)

**Comment by bonifarz** [comment]
Let me try to summarize again: There are variables *vartypes varnotypes varflags varnoflags* that allow advanced filtering when building the list of variables in the menu. These specify which variable types or flags are required or forbidden when listing the variables. That is, if I understood it correctly :wink:

**Comment by qreeves** [comment]
@bonifarz Maybe you should center the text and put the exclude checkbox on the other side of it.

@swooboo We can't really maintain a menu like the old one (if anyone noticed, it got outdated very quickly during development), which is why I created the new menu which maintains itself. Perhaps in the future we could create subset pages for weapon and game vars only which presents the information in an organised list, but still uses the vartype lookups to get the information.

**Comment by bonifarz** [comment]
Was just updating while you were commenting :smiley: 
As you can see, I thought of moving the advanced filter checkbox to the right, too, so it servers as sort of a title for the panel. That's how it looks now.
vars-preview
The extra checkbox for showing commands is still there, but only if the advanced panel is off.

**Comment by shirepirate** [comment]
still doesn't look like you've solved the problem of the confusion with why there are two checkboxes in front of each option. that's why qreeves suggested one of them go after the text. you've removed "exclude" entirely, so it's anyone's guess as to what it means at this point.

the vars menu should be as simple and intuitive as possible while still providing advanced functionality. when you make a change you need to think like a beginner that wants to change a variable, not going into it with the assumptions and knowledge you have.

that's why the 1.4 menu was popular and several have expressed wanting a reversion to a menu like this. as it's impossible to maintain such a style of format we'll eventually need to create groups to summarize each type of variable according to it's purpose & application.

**Comment by shirepirate** [comment]
also, for HEX flags (i'm going to assume these are probably all colors) it couldn't hurt to automatically add a color slider to apply a new option, similar to the profile menu

**Comment by bonifarz** [comment]
> should be as simple and intuitive as possible 

Very true, that's why the panel is disabled by default, while giving a simpler option for listing commands.
> you've removed "exclude" entirely

I thought it is better to explain each checkbox via the tooltip.
> Maybe you should center the text and put the exclude checkbox on the other side of it. 

Ah, now I see. Something like this?
vars-preview
I am not sure if that looks nicer, though.

RGB-sliders for the colours? I could try that, as there is enough of space.

**Comment by bonifarz** [comment]
vars-preview
I noticed I had some commented out block for issue #126. Tweaked this too, so it is somewhat useful. Easily removed if not wanted here. Also, if there's too many commits here, I can open another PR with a single commit.

**Comment by qreeves** [comment]
The number of commits is unimportant, so long as it doesn't contain duplicates of commits we've made to the main repo (eg. *git pull* without *--rebase*).

**Comment by qreeves** [comment]
I think a green '+' and a red/orange '-' at the top of the checkbox columns would fit the current iteration.

**Comment by bonifarz** [comment]
I like that idea. Tried it with normal (a bit small) and emphasis text (hard to align). I think icons of scale 0.5 work even better. What do you think?
vars-preview
And that's how the work-around for #126 looks. Shown for any ints that take less than 20 bits. Could that be useful, or shall i discard it again, so we can look for a clean solution later?

**Comment by bonifarz** [comment]
I think I found a nicer solution: Use a custom bitfield with different textures to exclude flags or types:

                        //guibitfield "" varnoflags (<< 1 $i) [ varnum = -1] 
                        guistayopen [ guiimage "textures/warning" [
                            varnoflags = (^ $varnoflags (<< 1 @i)) ; varnum = -1
                        ] 0.5 0 "" [] (? (& $varnoflags (<< 1 $i)) 0xff0000 0x999999)]

vars-preview
I just wonder, would that look better with this centered layout, or with the old, left adjusted double "checkboxes"? I guess the former is okay.

**Comment by qreeves** [comment]
I dunno, I guess we'll see.

**Comment by bonifarz** [comment]
Okay, thanks. If there are suggestions to further tweak the menu, it is no problem to push another PR with improvements.

**Pull request merged**
