### PR TITLE
new vegetation

### PR DESCRIPTION
**Pull request by q009**
Currently for new vegetation.

### CODE REVIEW

**Comment by shacknetisp** [comment]
Does anything need added to `config/`?

**Comment by q009** [comment]
No, it's entirely self-contained.
If a user wants to use the assets they will need to execute the supplied configs themselves.

**Comment by molexted** [comment]
Users won't likely execute the repository because they likely won't realize it's been added. Recommend adding entries to config/map/models.cfg.

**Comment by q009** [comment]
Very well

**Comment by shacknetisp** [comment]
Merged.

**Pull request closed without merging**
