### PR TITLE
demoautoclientsave variable, runs getdemo after every game if set

### PR DESCRIPTION
**Pull request by shacknetisp**
Breaks protocol.

### CODE REVIEW

**Comment by qreeves** [comment]
If you're going to make a new network command, you may as well replace the `srvoutf` by putting the info into the network packet instead.

**Comment by shacknetisp** [comment]
That would stop the message being written to the server output/IRC though.

**Comment by qreeves** [comment]
You'd replace it with a `relayf` in that case.

**Comment by qreeves** [comment]
Same deal, please rebase on master for merging.

**Pull request merged**
